server:
  port: 8889
spring:
  redis:
    host: 116.62.187.190
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 10s
        min-idle: 0
        max-idle: 8
merryyou:
  security:
    oauth2:
      storeType: redis #或者jwt
      jwtSigningKey: merryyou